.TH "Répertoire de référence de bdd" 3 "Jeudi 17 Décembre 2015" "Version dernière version" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de bdd \- 
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBAvis\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBAvis\&.h\fP"
.br
.ti -1c
.RI "fichier \fBCategorie\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBCategorie\&.h\fP"
.br
.ti -1c
.RI "fichier \fBCoordsBancaires\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBCoordsBancaires\&.h\fP"
.br
.ti -1c
.RI "fichier \fBEtatConnecte\&.h\fP"
.br
.ti -1c
.RI "fichier \fBEtatConnexion\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBEtatConnexion\&.h\fP"
.br
.ti -1c
.RI "fichier \fBEtatDeconnecte\&.h\fP"
.br
.ti -1c
.RI "fichier \fBEtatVente\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBEtatVente\&.h\fP"
.br
.ti -1c
.RI "fichier \fBGestionBdd\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBGestionBdd\&.h\fP"
.br
.ti -1c
.RI "fichier \fBLesProduits\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBLesProduits\&.h\fP"
.br
.ti -1c
.RI "fichier \fBLesUtilisateurs\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBLesUtilisateurs\&.h\fP"
.br
.ti -1c
.RI "fichier \fBProduit\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBProduit\&.h\fP"
.br
.ti -1c
.RI "fichier \fBUtilisateur\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBUtilisateur\&.h\fP"
.br
.ti -1c
.RI "fichier \fBVenteEnchere\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBVenteEnchere\&.h\fP"
.br
.ti -1c
.RI "fichier \fBVenteNormale\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBVenteNormale\&.h\fP"
.br
.in -1c
