.TH "CoordsBancaires" 3 "Jeudi 17 Décembre 2015" "Version dernière version" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoordsBancaires \- 
.PP
Cette classe contient les données bancaires d'un utilisateur\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CoordsBancaires\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCoordsBancaires\fP ()"
.br
.RI "\fIConstructeur de coordonnées bancaires\&. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Cette classe contient les données bancaires d'un utilisateur\&. 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CoordsBancaires::CoordsBancaires ()"

.PP
Constructeur de coordonnées bancaires\&. 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
