.TH "DialogAjouterVente.cpp" 3 "Jeudi 17 Décembre 2015" "Version dernière version" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogAjouterVente.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'DialogAjouterVente\&.h'\fP
.br
\fC#include 'ui_DialogAjouterVente\&.h'\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
