.TH "/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/code/EMarche/DialogInscription.h" 3 "Vendredi 18 Décembre 2015" "Version 6" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/code/EMarche/DialogInscription.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include 'bdd/GestionBdd\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDialogInscription\fP"
.br
.RI "\fIThe \fBDialogInscription\fP class - Boîte de dialogue permettant d'inscrire un nouvel utilisateur\&. \fP"
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
