.TH "DialogAjouterVente" 3 "Jeudi 17 Décembre 2015" "Version dernière version" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogAjouterVente \- 
.PP
The \fBDialogAjouterVente\fP class - Boîte de dialoque permettant l'ajout d'un produit en vente\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DialogAjouterVente\&.h>\fP
.PP
Est dérivée de QDialog\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBDialogAjouterVente\fP (\fBGestionBdd\fP *bdd, QWidget *parent=0)"
.br
.RI "\fI\fBDialogAjouterVente\fP - Constructeur\&. \fP"
.ti -1c
.RI "\fB~DialogAjouterVente\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
The \fBDialogAjouterVente\fP class - Boîte de dialoque permettant l'ajout d'un produit en vente\&. 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "DialogAjouterVente::DialogAjouterVente (\fBGestionBdd\fP *bdd, QWidget *parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBDialogAjouterVente\fP - Constructeur\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIbdd\fP - Lien vers \fBGestionBdd\fP qui gère toutes les données 
.br
\fIparent-\fP Lien vers le widget parent 
.RE
.PP

.SS "DialogAjouterVente::~DialogAjouterVente ()"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
