.TH "DialogAjouterVente.h" 3 "Jeudi 17 Décembre 2015" "Version dernière version" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogAjouterVente.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include 'bdd/GestionBdd\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDialogAjouterVente\fP"
.br
.RI "\fIThe \fBDialogAjouterVente\fP class - Boîte de dialoque permettant l'ajout d'un produit en vente\&. \fP"
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
