.TH "EtatDeconnecte" 3 "Jeudi 17 Décembre 2015" "Version dernière version" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EtatDeconnecte \- 
.PP
Cette classe gère les utilisateurs déconnectés\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EtatDeconnecte\&.h>\fP
.PP
Est dérivée de \fBEtatConnexion\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBEtatDeconnecte\fP (bool b)"
.br
.RI "\fIConstructeur de la classe \fBEtatDeconnecte\fP\&. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Cette classe gère les utilisateurs déconnectés\&. 

Elle hérite de la classe \fBEtatConnexion\fP 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "EtatDeconnecte::EtatDeconnecte (boolb)\fC [inline]\fP"

.PP
Constructeur de la classe \fBEtatDeconnecte\fP\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIb\fP - Nouvel état de connexion 
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
