.TH "bdd/EtatVente.h" 3 "Jeudi 17 Décembre 2015" "Version dernière version" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bdd/EtatVente.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEtatVente\fP"
.br
.RI "\fICette classe gère l'état d'une vente (enchère ou normale) \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
