.TH "bdd/GestionBdd.cpp" 3 "Jeudi 17 Décembre 2015" "Version dernière version" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bdd/GestionBdd.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'GestionBdd\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBvalRef\fP = 1"
.br
.ti -1c
.RI "string \fBnouvelleRef\fP = '#1'"
.br
.in -1c
.SH "Documentation des variables"
.PP 
.SS "string nouvelleRef = '#1'"

.SS "int valRef = 1"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
