.TH "bdd/LesUtilisateurs.h" 3 "Jeudi 17 Décembre 2015" "Version dernière version" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bdd/LesUtilisateurs.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'Utilisateur\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLesUtilisateurs\fP"
.br
.RI "\fIThe \fBLesUtilisateurs\fP class - Gère un vector de pointeurs vers des utilisateurs\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
