.TH "/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/iteration2/EMarche/bdd/Utilisateur.h" 3 "Vendredi 18 Décembre 2015" "Version 2" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/iteration2/EMarche/bdd/Utilisateur.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Produit\&.h'\fP
.br
\fC#include 'Avis\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUtilisateur\fP"
.br
.RI "\fIThe \fBUtilisateur\fP class - Contient toutes les informations personnelles d'un utilisateur\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
