.TH "MaFenetre" 3 "Thu Dec 17 2015" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaFenetre \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget, and \fBVue\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBafficherResUtilisateurs\fP (std::vector< Utilisateur * > v)"
.br
.ti -1c
.RI "void \fBafficherResProduits\fP (std::vector< Produit * > v)"
.br
.ti -1c
.RI "void \fBrechercher\fP ()"
.br
.ti -1c
.RI "void \fBaccueil\fP ()"
.br
.ti -1c
.RI "void \fBprofil\fP ()"
.br
.ti -1c
.RI "void \fBprofilAutreUtilisateur\fP (QString str)"
.br
.ti -1c
.RI "void \fBstatistiques\fP ()"
.br
.ti -1c
.RI "void \fBstatistiquesAutreUtilisateur\fP (QString str)"
.br
.ti -1c
.RI "void \fBventes\fP ()"
.br
.ti -1c
.RI "void \fBventesAutreUtilisateur\fP (QString str)"
.br
.ti -1c
.RI "void \fBachats\fP ()"
.br
.ti -1c
.RI "void \fBachatsAutreUtilisateur\fP (QString str)"
.br
.ti -1c
.RI "void \fBajouterVente\fP ()"
.br
.ti -1c
.RI "void \fBconnexion\fP ()"
.br
.ti -1c
.RI "void \fBmodificationProfil\fP ()"
.br
.ti -1c
.RI "void \fBvoirProduit\fP (QString ref)"
.br
.ti -1c
.RI "void \fBacheter\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBsignalRechercheUtilisateur\fP (std::vector< Utilisateur * > v)"
.br
.ti -1c
.RI "void \fBsignalRechercheProduits\fP (std::vector< Produit * > v)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaFenetre\fP (int l, int h, GestionBdd *bdd)"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBclearLayout\fP (QLayout *layout)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EMarche from the source code\&.
