.TH "Ui::DialogInscription" 3 "Thu Dec 17 2015" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::DialogInscription \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_DialogInscription\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for EMarche from the source code\&.
