.TH "Vue" 3 "Thu Dec 17 2015" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vue \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMaFenetre\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBupdate\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EMarche from the source code\&.
