.TH "/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/iteration4/EMarche/bdd/CoordsBancaires.h" 3 "Vendredi 18 Décembre 2015" "Version 4" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/iteration4/EMarche/bdd/CoordsBancaires.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCoordsBancaires\fP"
.br
.RI "\fICette classe contient les données bancaires d'un utilisateur\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
