.TH "/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/iteration4/EMarche/DialogModificationProfil.h" 3 "Vendredi 18 Décembre 2015" "Version 4" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/iteration4/EMarche/DialogModificationProfil.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include 'bdd/GestionBdd\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDialogModificationProfil\fP"
.br
.RI "\fIThe \fBDialogModificationProfil\fP class - Boîte de dialogue permettant de modifier les données du profil utilisateur\&. \fP"
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
