.TH "DialogModificationProfil" 3 "Vendredi 18 Décembre 2015" "Version 4" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogModificationProfil \- 
.PP
The \fBDialogModificationProfil\fP class - Boîte de dialogue permettant de modifier les données du profil utilisateur\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DialogModificationProfil\&.h>\fP
.PP
Est dérivée de QDialog\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBDialogModificationProfil\fP (\fBGestionBdd\fP *bdd, QWidget *parent=0)"
.br
.RI "\fI\fBDialogModificationProfil\fP - Constructeur\&. \fP"
.ti -1c
.RI "\fB~DialogModificationProfil\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
The \fBDialogModificationProfil\fP class - Boîte de dialogue permettant de modifier les données du profil utilisateur\&. 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "DialogModificationProfil::DialogModificationProfil (\fBGestionBdd\fP *bdd, QWidget *parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBDialogModificationProfil\fP - Constructeur\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIbdd\fP - Lien vers \fBGestionBdd\fP qui contient toutes les données 
.br
\fIparent\fP - Lien vers le widget parent 
.RE
.PP

.SS "DialogModificationProfil::~DialogModificationProfil ()"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
