.TH "/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/iteration4/EMarche/DialogInscription.cpp" 3 "Vendredi 18 Décembre 2015" "Version 4" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/iteration4/EMarche/DialogInscription.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'DialogInscription\&.h'\fP
.br
\fC#include 'ui_DialogInscription\&.h'\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
