.TH "/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/iteration4/EMarche/bdd/EtatConnexion.h" 3 "Vendredi 18 Décembre 2015" "Version 4" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/iteration4/EMarche/bdd/EtatConnexion.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEtatConnexion\fP"
.br
.RI "\fICette classe gère les états de connexion d'un utilisateur (connecté ou déconnecté) \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
