.TH "Ui" 3 "Vendredi 18 Décembre 2015" "Version 4" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDialogAcheter\fP"
.br
.ti -1c
.RI "class \fBDialogAjouterVente\fP"
.br
.ti -1c
.RI "class \fBDialogConnexion\fP"
.br
.ti -1c
.RI "class \fBDialogInscription\fP"
.br
.ti -1c
.RI "class \fBDialogModificationProfil\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
