.TH "Utilisateur" 3 "Vendredi 18 Décembre 2015" "Version 4" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utilisateur \- 
.PP
The \fBUtilisateur\fP class - Contient toutes les informations personnelles d'un utilisateur\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Utilisateur\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBUtilisateur\fP (std::string monPseudo, std::string monMdp, std::string name, std::string firstname, int jourNaiss, int moisNaiss, int anneeNaiss, std::string mail, std::string adr, int cP)"
.br
.RI "\fI\fBUtilisateur\fP - Constructeur\&. \fP"
.ti -1c
.RI "\fBUtilisateur\fP ()"
.br
.RI "\fI\fBUtilisateur\fP - Constructeur vide\&. \fP"
.ti -1c
.RI "\fB~Utilisateur\fP ()"
.br
.ti -1c
.RI "std::string \fBgetPseudo\fP ()"
.br
.RI "\fIgetPseudo \fP"
.ti -1c
.RI "std::string \fBgetMdp\fP ()"
.br
.RI "\fIgetMdp \fP"
.ti -1c
.RI "std::string \fBgetNom\fP ()"
.br
.RI "\fIgetNom \fP"
.ti -1c
.RI "std::string \fBgetPrenom\fP ()"
.br
.RI "\fIgetPrenom \fP"
.ti -1c
.RI "std::string \fBgetDateNaissance\fP ()"
.br
.RI "\fIgetDateNaissance \fP"
.ti -1c
.RI "std::string \fBgetEmail\fP ()"
.br
.RI "\fIgetEmail \fP"
.ti -1c
.RI "std::string \fBgetAdresse\fP ()"
.br
.RI "\fIgetAdresse \fP"
.ti -1c
.RI "std::string \fBgetVille\fP ()"
.br
.RI "\fIgetVille \fP"
.ti -1c
.RI "int \fBgetCodePostal\fP ()"
.br
.RI "\fIgetCodePostal \fP"
.ti -1c
.RI "unsigned int \fBgetNbVentes\fP ()"
.br
.RI "\fIgetNbVentes \fP"
.ti -1c
.RI "unsigned int \fBgetNbAchats\fP ()"
.br
.RI "\fIgetNbAchats \fP"
.ti -1c
.RI "unsigned int \fBgetNote\fP ()"
.br
.RI "\fIgetNote \fP"
.ti -1c
.RI "std::vector< \fBProduit\fP * > \fBgetLesAchats\fP ()"
.br
.RI "\fIgetLesAchats \fP"
.ti -1c
.RI "std::vector< \fBProduit\fP * > \fBgetLesVentes\fP ()"
.br
.RI "\fIgetLesVentes \fP"
.ti -1c
.RI "std::vector< \fBAvis\fP > \fBgetLesAvis\fP ()"
.br
.RI "\fIgetLesAvis \fP"
.ti -1c
.RI "void \fBsetPseudo\fP (std::string p)"
.br
.RI "\fIsetPseudo \fP"
.ti -1c
.RI "void \fBsetMdp\fP (std::string m)"
.br
.RI "\fIsetMdp \fP"
.ti -1c
.RI "void \fBsetNom\fP (std::string n)"
.br
.RI "\fIsetNom \fP"
.ti -1c
.RI "void \fBsetPrenom\fP (std::string p)"
.br
.RI "\fIsetPrenom \fP"
.ti -1c
.RI "void \fBsetDateNaissance\fP (int jour, int mois, int annee)"
.br
.RI "\fIsetDateNaissance \fP"
.ti -1c
.RI "void \fBsetEmail\fP (std::string e)"
.br
.RI "\fIsetEmail \fP"
.ti -1c
.RI "void \fBsetAdresse\fP (std::string a)"
.br
.RI "\fIsetAdresse \fP"
.ti -1c
.RI "void \fBsetCodePostal\fP (int i)"
.br
.RI "\fIsetCodePostal \fP"
.ti -1c
.RI "void \fBsetVille\fP (std::string v)"
.br
.RI "\fIsetVille \fP"
.ti -1c
.RI "void \fBsetNbVentes\fP (unsigned int n)"
.br
.RI "\fIsetNbVentes \fP"
.ti -1c
.RI "void \fBsetNbAchats\fP (unsigned int n)"
.br
.RI "\fIsetNbAchats \fP"
.ti -1c
.RI "void \fBsetNote\fP (unsigned int n)"
.br
.RI "\fIsetNote \fP"
.ti -1c
.RI "void \fBaddAchat\fP (\fBProduit\fP *p, int quantite)"
.br
.RI "\fIaddAchat \fP"
.ti -1c
.RI "void \fBaddVente\fP (\fBProduit\fP *p)"
.br
.RI "\fIaddVente \fP"
.ti -1c
.RI "void \fBaddAvis\fP (\fBAvis\fP a)"
.br
.RI "\fIaddAvis \fP"
.ti -1c
.RI "void \fBdecrit\fP (std::ostream &os)"
.br
.RI "\fIdecrit - Ecrit toutes les données utilisateur dans un flux donné en paramètre \fP"
.ti -1c
.RI "std::string \fBdecrit\fP ()"
.br
.RI "\fIdecrit - convertit un flux en string \fP"
.ti -1c
.RI "void \fBaffiche\fP (std::ostream &os)"
.br
.RI "\fIaffiche - Ecrit toutes les données utilisateur d'un flux vers une sortie \fP"
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "std::string \fBpseudo\fP"
.br
.ti -1c
.RI "std::string \fBmdp\fP"
.br
.ti -1c
.RI "std::string \fBnom\fP"
.br
.ti -1c
.RI "std::string \fBprenom\fP"
.br
.ti -1c
.RI "struct tm \fBdateNaissance\fP"
.br
.ti -1c
.RI "std::string \fBemail\fP"
.br
.ti -1c
.RI "std::string \fBadresse\fP"
.br
.ti -1c
.RI "std::string \fBville\fP"
.br
.ti -1c
.RI "unsigned int \fBnbVentes\fP"
.br
.ti -1c
.RI "unsigned int \fBnbAchats\fP"
.br
.ti -1c
.RI "unsigned int \fBnbAvis\fP"
.br
.ti -1c
.RI "unsigned int \fBnote\fP"
.br
.ti -1c
.RI "unsigned int \fBnbNotes\fP"
.br
.ti -1c
.RI "int \fBcodePostal\fP"
.br
.ti -1c
.RI "std::vector< \fBProduit\fP * > \fBlesAchats\fP"
.br
.ti -1c
.RI "std::vector< \fBProduit\fP * > \fBlesVentes\fP"
.br
.ti -1c
.RI "std::vector< \fBAvis\fP > \fBlesAvis\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
The \fBUtilisateur\fP class - Contient toutes les informations personnelles d'un utilisateur\&. 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Utilisateur::Utilisateur (std::stringmonPseudo, std::stringmonMdp, std::stringname, std::stringfirstname, intjourNaiss, intmoisNaiss, intanneeNaiss, std::stringmail, std::stringadr, intcP)\fC [inline]\fP"

.PP
\fBUtilisateur\fP - Constructeur\&. 
.PP
\fBParamètres:\fP
.RS 4
\fImonPseudo\fP - Pseudo de l'utilisateur 
.br
\fImonMdp\fP - Mot de passe de l'utilisateur 
.br
\fIname\fP - Nom de l'utilisateur 
.br
\fIfirstname\fP - Prénom de l'utilisateur 
.br
\fIjourNaiss\fP - Jour de naissance de l'utilisateur 
.br
\fImoisNaiss\fP - Mois de naissance de l'utilisateur 
.br
\fIanneeNaiss\fP - Année de naissance de l'utilisateur 
.br
\fImail\fP - Adresse mail de l'utilisateur 
.br
\fIadr\fP - Adresse de l'utilisateur 
.br
\fIcP\fP - Code postal de l'utilisateur 
.RE
.PP

.SS "Utilisateur::Utilisateur ()\fC [inline]\fP"

.PP
\fBUtilisateur\fP - Constructeur vide\&. 
.SS "Utilisateur::~Utilisateur ()\fC [inline]\fP"

.SH "Documentation des fonctions membres"
.PP 
.SS "void Utilisateur::addAchat (\fBProduit\fP *p, intquantite)"

.PP
addAchat 
.PP
\fBParamètres:\fP
.RS 4
\fIp\fP - Pointeur vers le nouveau produit à ajouter aux achats 
.RE
.PP

.SS "void Utilisateur::addAvis (\fBAvis\fPa)"

.PP
addAvis 
.PP
\fBParamètres:\fP
.RS 4
\fIa\fP - \fBAvis\fP à ajouter à l'utilisateur dans le vector lesAvis 
.RE
.PP

.SS "void Utilisateur::addVente (\fBProduit\fP *p)"

.PP
addVente 
.PP
\fBParamètres:\fP
.RS 4
\fIp\fP - Pointeur vers le nouveau produit à ajouter aux ventes 
.RE
.PP

.SS "void Utilisateur::affiche (std::ostream &os)\fC [inline]\fP"

.PP
affiche - Ecrit toutes les données utilisateur d'un flux vers une sortie 
.PP
\fBParamètres:\fP
.RS 4
\fIos\fP - Sortie, par exemple : cout 
.RE
.PP

.SS "void Utilisateur::decrit (std::ostream &os)\fC [inline]\fP"

.PP
decrit - Ecrit toutes les données utilisateur dans un flux donné en paramètre 
.PP
\fBParamètres:\fP
.RS 4
\fIos\fP - Flux 
.RE
.PP

.SS "std::string Utilisateur::decrit ()\fC [inline]\fP"

.PP
decrit - convertit un flux en string 
.PP
\fBRenvoie:\fP
.RS 4
un string à partir d'un flux 
.RE
.PP

.SS "std::string Utilisateur::getAdresse ()"

.PP
getAdresse 
.PP
\fBRenvoie:\fP
.RS 4
l'adresse de l'utilisateur 
.RE
.PP

.SS "int Utilisateur::getCodePostal ()"

.PP
getCodePostal 
.PP
\fBRenvoie:\fP
.RS 4
le code postal de l'utilisateur 
.RE
.PP

.SS "std::string Utilisateur::getDateNaissance ()"

.PP
getDateNaissance 
.PP
\fBRenvoie:\fP
.RS 4
la date de naissance de l'utilisateur sous forme de string 
.RE
.PP

.SS "std::string Utilisateur::getEmail ()"

.PP
getEmail 
.PP
\fBRenvoie:\fP
.RS 4
l'adresse e-mail de l'utilisatueur 
.RE
.PP

.SS "std::vector< \fBProduit\fP * > Utilisateur::getLesAchats ()"

.PP
getLesAchats 
.PP
\fBRenvoie:\fP
.RS 4
un vector contenant les pointeurs vers les achats de l'utilisateur 
.RE
.PP

.SS "std::vector< \fBAvis\fP > Utilisateur::getLesAvis ()"

.PP
getLesAvis 
.PP
\fBRenvoie:\fP
.RS 4
les avis sur l'utilisateur 
.RE
.PP

.SS "std::vector< \fBProduit\fP * > Utilisateur::getLesVentes ()"

.PP
getLesVentes 
.PP
\fBRenvoie:\fP
.RS 4
un vector contenant les pointeurs vers les ventes de l'utilisateur 
.RE
.PP

.SS "std::string Utilisateur::getMdp ()"

.PP
getMdp 
.PP
\fBRenvoie:\fP
.RS 4
le mot de passe de l'utilisateur 
.RE
.PP

.SS "unsigned int Utilisateur::getNbAchats ()"

.PP
getNbAchats 
.PP
\fBRenvoie:\fP
.RS 4
le nombre d'achats de l'utilisateur 
.RE
.PP

.SS "unsigned int Utilisateur::getNbVentes ()"

.PP
getNbVentes 
.PP
\fBRenvoie:\fP
.RS 4
le nombre de ventes de l'utilisateur 
.RE
.PP

.SS "std::string Utilisateur::getNom ()"

.PP
getNom 
.PP
\fBRenvoie:\fP
.RS 4
le nom de l'utilisateur 
.RE
.PP

.SS "unsigned int Utilisateur::getNote ()"

.PP
getNote 
.PP
\fBRenvoie:\fP
.RS 4
la note de l'utilisateur attribuée par les autres utilisateurs 
.RE
.PP

.SS "std::string Utilisateur::getPrenom ()"

.PP
getPrenom 
.PP
\fBRenvoie:\fP
.RS 4
le prénom de l'utilisateur 
.RE
.PP

.SS "std::string Utilisateur::getPseudo ()"

.PP
getPseudo 
.PP
\fBRenvoie:\fP
.RS 4
le pseudo de l'utilisateur 
.RE
.PP

.SS "std::string Utilisateur::getVille ()"

.PP
getVille 
.PP
\fBRenvoie:\fP
.RS 4
la ville de l'utilisateur 
.RE
.PP

.SS "void Utilisateur::setAdresse (std::stringa)"

.PP
setAdresse 
.PP
\fBParamètres:\fP
.RS 4
\fIa\fP - nouvelle adresse 
.RE
.PP

.SS "void Utilisateur::setCodePostal (inti)"

.PP
setCodePostal 
.PP
\fBParamètres:\fP
.RS 4
\fIi\fP - nouveau code postal 
.RE
.PP

.SS "void Utilisateur::setDateNaissance (intjour, intmois, intannee)"

.PP
setDateNaissance 
.PP
\fBParamètres:\fP
.RS 4
\fIjour\fP - nouveau jour de naissance 
.br
\fImois\fP - nouveau mois de naissance 
.br
\fIannee\fP - nouvelle année de naissance 
.RE
.PP

.SS "void Utilisateur::setEmail (std::stringe)"

.PP
setEmail 
.PP
\fBParamètres:\fP
.RS 4
\fIe\fP - nouvelle adresse e-mail 
.RE
.PP

.SS "void Utilisateur::setMdp (std::stringm)"

.PP
setMdp 
.PP
\fBParamètres:\fP
.RS 4
\fIm\fP - nouveau mot de passe 
.RE
.PP

.SS "void Utilisateur::setNbAchats (unsigned intn)"

.PP
setNbAchats 
.PP
\fBParamètres:\fP
.RS 4
\fIn\fP - nouveau nombre d'achats 
.RE
.PP

.SS "void Utilisateur::setNbVentes (unsigned intn)"

.PP
setNbVentes 
.PP
\fBParamètres:\fP
.RS 4
\fIn\fP - nouveau nombre de ventes 
.RE
.PP

.SS "void Utilisateur::setNom (std::stringn)"

.PP
setNom 
.PP
\fBParamètres:\fP
.RS 4
\fIn\fP - nouveau nom 
.RE
.PP

.SS "void Utilisateur::setNote (unsigned intn)"

.PP
setNote 
.PP
\fBParamètres:\fP
.RS 4
\fIn\fP - nouvelle note 
.RE
.PP

.SS "void Utilisateur::setPrenom (std::stringp)"

.PP
setPrenom 
.PP
\fBParamètres:\fP
.RS 4
\fIp\fP - nouveau prénom 
.RE
.PP

.SS "void Utilisateur::setPseudo (std::stringp)"

.PP
setPseudo 
.PP
\fBParamètres:\fP
.RS 4
\fIp\fP - nouveau pseudo 
.RE
.PP

.SS "void Utilisateur::setVille (std::stringv)"

.PP
setVille 
.PP
\fBParamètres:\fP
.RS 4
\fIv\fP - nouvelle ville 
.RE
.PP

.SH "Documentation des données membres"
.PP 
.SS "std::string Utilisateur::adresse\fC [protected]\fP"

.SS "int Utilisateur::codePostal\fC [protected]\fP"

.SS "struct tm Utilisateur::dateNaissance\fC [protected]\fP"

.SS "std::string Utilisateur::email\fC [protected]\fP"

.SS "std::vector<\fBProduit\fP*> Utilisateur::lesAchats\fC [protected]\fP"

.SS "std::vector<\fBAvis\fP> Utilisateur::lesAvis\fC [protected]\fP"

.SS "std::vector<\fBProduit\fP*> Utilisateur::lesVentes\fC [protected]\fP"

.SS "std::string Utilisateur::mdp\fC [protected]\fP"

.SS "unsigned int Utilisateur::nbAchats\fC [protected]\fP"

.SS "unsigned int Utilisateur::nbAvis\fC [protected]\fP"

.SS "unsigned int Utilisateur::nbNotes\fC [protected]\fP"

.SS "unsigned int Utilisateur::nbVentes\fC [protected]\fP"

.SS "std::string Utilisateur::nom\fC [protected]\fP"

.SS "unsigned int Utilisateur::note\fC [protected]\fP"

.SS "std::string Utilisateur::prenom\fC [protected]\fP"

.SS "std::string Utilisateur::pseudo\fC [protected]\fP"

.SS "std::string Utilisateur::ville\fC [protected]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
