.TH "DialogAcheter" 3 "Vendredi 18 Décembre 2015" "Version 3" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogAcheter \- 
.PP
Boîte de dialogue permettant d'acheter un produit\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DialogAcheter\&.h>\fP
.PP
Est dérivée de QDialog\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBDialogAcheter\fP (\fBGestionBdd\fP *bdd, QWidget *parent=0)"
.br
.RI "\fIConstructeur de \fBDialogAcheter\fP\&. \fP"
.ti -1c
.RI "\fB~DialogAcheter\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Boîte de dialogue permettant d'acheter un produit\&. 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "DialogAcheter::DialogAcheter (\fBGestionBdd\fP *bdd, QWidget *parent = \fC0\fP)\fC [explicit]\fP"

.PP
Constructeur de \fBDialogAcheter\fP\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIbdd\fP - Lien vers \fBGestionBdd\fP qui gère toutes les données 
.br
\fIparent-\fP Lien vers le widget parent 
.RE
.PP

.SS "DialogAcheter::~DialogAcheter ()"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
