.TH "/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/iteration3/EMarche/DialogAcheter.h" 3 "Vendredi 18 Décembre 2015" "Version 3" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/iteration3/EMarche/DialogAcheter.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include 'bdd/GestionBdd\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDialogAcheter\fP"
.br
.RI "\fIBoîte de dialogue permettant d'acheter un produit\&. \fP"
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
