.TH "LesUtilisateurs" 3 "Vendredi 18 Décembre 2015" "Version 3" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LesUtilisateurs \- 
.PP
The \fBLesUtilisateurs\fP class - Gère un vector de pointeurs vers des utilisateurs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LesUtilisateurs\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBLesUtilisateurs\fP ()"
.br
.RI "\fI\fBLesUtilisateurs\fP - Constructeur\&. \fP"
.ti -1c
.RI "\fB~LesUtilisateurs\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (\fBUtilisateur\fP *u)"
.br
.RI "\fIadd - Ajoute un pointeur vers un utilisateur dans le vector lesUtilisateurs \fP"
.ti -1c
.RI "void \fBsupprimer\fP (std::string pseudo)"
.br
.RI "\fIsupprimer - Supprime un utilisateur du vector lesUtilisateurs via son pseudo \fP"
.ti -1c
.RI "\fBUtilisateur\fP * \fBgetUtilisateur\fP (std::string pseudo)"
.br
.RI "\fIgetUtilisateur - Retourne un pointeur vers un utilisateur du vector lesUtilisateurs via son pseudo \fP"
.ti -1c
.RI "bool \fBexisteUtilisateur\fP (std::string pseudo, std::string mdp)"
.br
.RI "\fIexisteUtilisateur dit si l'utilisateur existe ou non via son pseudo et mot de passe \fP"
.ti -1c
.RI "int \fBgetNbUtilisateurs\fP ()"
.br
.RI "\fIgetNbUtilisateurs \fP"
.ti -1c
.RI "void \fBaffiche\fP ()"
.br
.RI "\fIaffiche tous les utilisateurs \fP"
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "std::vector< \fBUtilisateur\fP * > \fBlesUtilisateurs\fP"
.br
.ti -1c
.RI "int \fBnbUtilisateurs\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
The \fBLesUtilisateurs\fP class - Gère un vector de pointeurs vers des utilisateurs\&. 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "LesUtilisateurs::LesUtilisateurs ()\fC [inline]\fP"

.PP
\fBLesUtilisateurs\fP - Constructeur\&. 
.SS "LesUtilisateurs::~LesUtilisateurs ()\fC [inline]\fP"

.SH "Documentation des fonctions membres"
.PP 
.SS "void LesUtilisateurs::add (\fBUtilisateur\fP *u)"

.PP
add - Ajoute un pointeur vers un utilisateur dans le vector lesUtilisateurs 
.PP
\fBParamètres:\fP
.RS 4
\fIu\fP - Pointeur vers l'utilisateur à ajouter 
.RE
.PP

.SS "void LesUtilisateurs::affiche ()"

.PP
affiche tous les utilisateurs 
.SS "bool LesUtilisateurs::existeUtilisateur (std::stringpseudo, std::stringmdp)"

.PP
existeUtilisateur dit si l'utilisateur existe ou non via son pseudo et mot de passe 
.PP
\fBParamètres:\fP
.RS 4
\fIpseudo\fP - Pseudo de l'utilisateur recherché 
.br
\fImdp\fP - Mot de passe de l'utilisateur recherché 
.RE
.PP
\fBRenvoie:\fP
.RS 4
true si l'utilisateur existe, false sinon 
.RE
.PP

.SS "int LesUtilisateurs::getNbUtilisateurs ()"

.PP
getNbUtilisateurs 
.PP
\fBRenvoie:\fP
.RS 4

.RE
.PP

.SS "\fBUtilisateur\fP * LesUtilisateurs::getUtilisateur (std::stringpseudo)"

.PP
getUtilisateur - Retourne un pointeur vers un utilisateur du vector lesUtilisateurs via son pseudo 
.PP
\fBParamètres:\fP
.RS 4
\fIpseudo\fP - Pseudo de l'utilisateur à renvoyer 
.RE
.PP
\fBRenvoie:\fP
.RS 4
un pointeur vers l'utilisateur recherché 
.RE
.PP

.SS "void LesUtilisateurs::supprimer (std::stringpseudo)"

.PP
supprimer - Supprime un utilisateur du vector lesUtilisateurs via son pseudo 
.PP
\fBParamètres:\fP
.RS 4
\fIpseudo\fP - Pseudo de l'utilisateur à supprimer 
.RE
.PP

.SH "Documentation des données membres"
.PP 
.SS "std::vector<\fBUtilisateur\fP*> LesUtilisateurs::lesUtilisateurs\fC [protected]\fP"

.SS "int LesUtilisateurs::nbUtilisateurs\fC [protected]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
