.TH "/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/iteration3/EMarche/bdd/VenteNormale.h" 3 "Vendredi 18 Décembre 2015" "Version 3" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/iteration3/EMarche/bdd/VenteNormale.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'EtatVente\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVenteNormale\fP"
.br
.RI "\fICette classe gère une vente normale\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
