.TH "Répertoire de référence de /home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/itération5/EMarche" 3 "Vendredi 18 Décembre 2015" "Version 5" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de /home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/itération5/EMarche \- 
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBbdd\fP"
.br
.in -1c
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBDialogAcheter\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBDialogAcheter\&.h\fP"
.br
.ti -1c
.RI "fichier \fBDialogAjouterVente\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBDialogAjouterVente\&.h\fP"
.br
.ti -1c
.RI "fichier \fBDialogConnexion\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBDialogConnexion\&.h\fP"
.br
.ti -1c
.RI "fichier \fBDialogInscription\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBDialogInscription\&.h\fP"
.br
.ti -1c
.RI "fichier \fBDialogModificationProfil\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBDialogModificationProfil\&.h\fP"
.br
.ti -1c
.RI "fichier \fBMaFenetre\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBMaFenetre\&.h\fP"
.br
.ti -1c
.RI "fichier \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBui_DialogAcheter\&.h\fP"
.br
.ti -1c
.RI "fichier \fBui_DialogAjouterVente\&.h\fP"
.br
.ti -1c
.RI "fichier \fBui_DialogConnexion\&.h\fP"
.br
.ti -1c
.RI "fichier \fBui_DialogInscription\&.h\fP"
.br
.ti -1c
.RI "fichier \fBui_DialogModificationProfil\&.h\fP"
.br
.ti -1c
.RI "fichier \fBVue\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBVue\&.h\fP"
.br
.in -1c
