.TH "Categorie" 3 "Vendredi 18 Décembre 2015" "Version 5" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Categorie \- 
.PP
The \fBCategorie\fP class - Représente une catégorie de produits\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Categorie\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCategorie\fP (std::string n)"
.br
.RI "\fI\fBCategorie\fP\&. \fP"
.ti -1c
.RI "virtual \fB~Categorie\fP ()"
.br
.ti -1c
.RI "std::string \fBgetNom\fP ()"
.br
.RI "\fIgetNom \fP"
.ti -1c
.RI "void \fBsetNom\fP (std::string n)"
.br
.RI "\fIsetNom \fP"
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "std::string \fBnom\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
The \fBCategorie\fP class - Représente une catégorie de produits\&. 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Categorie::Categorie (std::stringn)\fC [inline]\fP"

.PP
\fBCategorie\fP\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIn\fP - Nom de la catégorie 
.RE
.PP

.SS "virtual Categorie::~Categorie ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Documentation des fonctions membres"
.PP 
.SS "string Categorie::getNom ()"

.PP
getNom 
.PP
\fBRenvoie:\fP
.RS 4
le nom de la catégorie 
.RE
.PP

.SS "void Categorie::setNom (std::stringn)"

.PP
setNom 
.PP
\fBParamètres:\fP
.RS 4
\fIn\fP - nouveau nom de la catégorie 
.RE
.PP

.SH "Documentation des données membres"
.PP 
.SS "std::string Categorie::nom\fC [protected]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
