.TH "EtatConnecte" 3 "Vendredi 18 Décembre 2015" "Version 5" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EtatConnecte \- 
.PP
Cette classe gère les utilisateurs connectés\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EtatConnecte\&.h>\fP
.PP
Est dérivée de \fBEtatConnexion\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBEtatConnecte\fP (bool b)"
.br
.RI "\fIConstructeur de la classe \fBEtatConnecte\fP\&. \fP"
.ti -1c
.RI "virtual \fB~EtatConnecte\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Cette classe gère les utilisateurs connectés\&. 

Elle hérite de la classe \fBEtatConnexion\fP 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "EtatConnecte::EtatConnecte (boolb)\fC [inline]\fP"

.PP
Constructeur de la classe \fBEtatConnecte\fP\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIb\fP - Nouvel état de connexion 
.RE
.PP

.SS "virtual EtatConnecte::~EtatConnecte ()\fC [inline]\fP, \fC [virtual]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
