.TH "/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/itération5/EMarche/MaFenetre.h" 3 "Vendredi 18 Décembre 2015" "Version 5" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/itération5/EMarche/MaFenetre.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QComboBox>\fP
.br
\fC#include <QLineEdit>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QScrollArea>\fP
.br
\fC#include <QCoreApplication>\fP
.br
\fC#include <QHBoxLayout>\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QGridLayout>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QGroupBox>\fP
.br
\fC#include <QSpinBox>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QSignalMapper>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'DialogConnexion\&.h'\fP
.br
\fC#include 'DialogInscription\&.h'\fP
.br
\fC#include 'DialogAjouterVente\&.h'\fP
.br
\fC#include 'DialogModificationProfil\&.h'\fP
.br
\fC#include 'DialogAcheter\&.h'\fP
.br
\fC#include 'Vue\&.h'\fP
.br
\fC#include 'bdd/GestionBdd\&.h'\fP
.br
\fC#include 'bdd/LesUtilisateurs\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaFenetre\fP"
.br
.RI "\fIThe \fBMaFenetre\fP class - Affichage principal de l'application\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
