.TH "Ui::DialogAcheter" 3 "Vendredi 18 Décembre 2015" "Version 5" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::DialogAcheter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_DialogAcheter\&.h>\fP
.PP
Est dérivée de \fBUi_DialogAcheter\fP\&.
.SS "Membres hérités additionnels"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
