.TH "/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/itération5/EMarche/Vue.cpp" 3 "Vendredi 18 Décembre 2015" "Version 5" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/magalie/Bureau/S5/CPOOA/Projet/E-Marche-/iterations/itération5/EMarche/Vue.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Vue\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
