.TH "Vue" 3 "Vendredi 18 Décembre 2015" "Version 5" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vue \- 
.PP
The \fBVue\fP class - Permet la mise à jour des vues\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Vue\&.h>\fP
.PP
Dérivée par \fBMaFenetre\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "virtual \fB~Vue\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdate\fP ()=0"
.br
.RI "\fIupdate - Mise à jour \fP"
.in -1c
.SH "Description détaillée"
.PP 
The \fBVue\fP class - Permet la mise à jour des vues\&. 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "virtual Vue::~Vue ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Documentation des fonctions membres"
.PP 
.SS "virtual void Vue::update ()\fC [pure virtual]\fP"

.PP
update - Mise à jour 
.PP
Implémenté dans \fBMaFenetre\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EMarche à partir du code source\&.
