.TH "Avis" 3 "Thu Dec 17 2015" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Avis \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAvis\fP (std::string author, unsigned int notation)"
.br
.ti -1c
.RI "\fBAvis\fP (std::string author, unsigned int notation, std::string com)"
.br
.ti -1c
.RI "unsigned int \fBgetNote\fP ()"
.br
.ti -1c
.RI "std::string \fBgetCommentaire\fP ()"
.br
.ti -1c
.RI "std::string \fBgetAuteur\fP ()"
.br
.ti -1c
.RI "void \fBdecrit\fP (std::ostream &os)"
.br
.ti -1c
.RI "std::string \fBdecrit\fP ()"
.br
.ti -1c
.RI "void \fBaffiche\fP (std::ostream &os)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EMarche from the source code\&.
