.TH "Categorie" 3 "Thu Dec 17 2015" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Categorie \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCategorie\fP (std::string n)"
.br
.ti -1c
.RI "std::string \fBgetNom\fP ()"
.br
.ti -1c
.RI "void \fBsetNom\fP (std::string n)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EMarche from the source code\&.
