.TH "EtatConnecte" 3 "Thu Dec 17 2015" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EtatConnecte \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEtatConnexion\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEtatConnecte\fP (bool b)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EMarche from the source code\&.
