.TH "EtatConnexion" 3 "Thu Dec 17 2015" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EtatConnexion \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBEtatConnecte\fP, and \fBEtatDeconnecte\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEtatConnexion\fP (bool b)"
.br
.ti -1c
.RI "bool \fBconnexionEnCours\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EMarche from the source code\&.
