.TH "LesProduits" 3 "Thu Dec 17 2015" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LesProduits \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::vector< \fBProduit\fP * > \fBgetListProduits\fP ()"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "void \fBaddProduit\fP (\fBProduit\fP *p)"
.br
.ti -1c
.RI "void \fBsupprimerProduit\fP (std::string ref)"
.br
.ti -1c
.RI "void \fBsupprimerProduit\fP (\fBProduit\fP *p)"
.br
.ti -1c
.RI "std::vector< \fBProduit\fP * > \fBgetProduitsNom\fP (std::string chaine)"
.br
.ti -1c
.RI "\fBProduit\fP * \fBgetProduit\fP (std::string ref)"
.br
.ti -1c
.RI "std::vector< \fBProduit\fP * > \fBrechercherTags\fP (std::string t)"
.br
.ti -1c
.RI "std::vector< \fBProduit\fP * > \fBrechercherCategorie\fP (std::string t)"
.br
.ti -1c
.RI "std::vector< \fBProduit\fP * > \fBrechercherTags\fP (std::vector< std::string >)"
.br
.ti -1c
.RI "void \fBtriPrixCroissant\fP ()"
.br
.ti -1c
.RI "void \fBtoString\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EMarche from the source code\&.
