.TH "LesUtilisateurs" 3 "Thu Dec 17 2015" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LesUtilisateurs \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd\fP (\fBUtilisateur\fP *u)"
.br
.ti -1c
.RI "void \fBsupprimer\fP (std::string pseudo)"
.br
.ti -1c
.RI "\fBUtilisateur\fP * \fBgetUtilisateur\fP (std::string pseudo)"
.br
.ti -1c
.RI "std::vector< \fBUtilisateur\fP * > \fBgetUtilisateurs\fP (std::string chaine)"
.br
.ti -1c
.RI "bool \fBexisteUtilisateur\fP (std::string pseudo, std::string mdp)"
.br
.ti -1c
.RI "int \fBgetNbUtilisateurs\fP ()"
.br
.ti -1c
.RI "void \fBaffiche\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EMarche from the source code\&.
