.TH "Utilisateur" 3 "Thu Dec 17 2015" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utilisateur \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUtilisateur\fP (std::string monPseudo, std::string monMdp, std::string name, std::string firstname, int jourNaiss, int moisNaiss, int anneeNaiss, std::string mail, std::string adr, int cP)"
.br
.ti -1c
.RI "std::string \fBgetPseudo\fP ()"
.br
.ti -1c
.RI "std::string \fBgetMdp\fP ()"
.br
.ti -1c
.RI "std::string \fBgetNom\fP ()"
.br
.ti -1c
.RI "std::string \fBgetPrenom\fP ()"
.br
.ti -1c
.RI "std::string \fBgetDateNaissance\fP ()"
.br
.ti -1c
.RI "std::string \fBgetEmail\fP ()"
.br
.ti -1c
.RI "std::string \fBgetAdresse\fP ()"
.br
.ti -1c
.RI "std::string \fBgetVille\fP ()"
.br
.ti -1c
.RI "int \fBgetCodePostal\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetNbVentes\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetNbAchats\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetNote\fP ()"
.br
.ti -1c
.RI "std::vector< \fBProduit\fP * > \fBgetLesAchats\fP ()"
.br
.ti -1c
.RI "std::vector< \fBProduit\fP * > \fBgetLesVentes\fP ()"
.br
.ti -1c
.RI "std::vector< \fBAvis\fP > \fBgetLesAvis\fP ()"
.br
.ti -1c
.RI "void \fBgetLesAvis\fP (unsigned int deb, unsigned int nb)"
.br
.ti -1c
.RI "void \fBsetPseudo\fP (std::string p)"
.br
.ti -1c
.RI "void \fBsetMdp\fP (std::string m)"
.br
.ti -1c
.RI "void \fBsetNom\fP (std::string n)"
.br
.ti -1c
.RI "void \fBsetPrenom\fP (std::string p)"
.br
.ti -1c
.RI "void \fBsetDateNaissance\fP (int jour, int mois, int annee)"
.br
.ti -1c
.RI "void \fBsetEmail\fP (std::string e)"
.br
.ti -1c
.RI "void \fBsetAdresse\fP (std::string a)"
.br
.ti -1c
.RI "void \fBsetCodePostal\fP (int i)"
.br
.ti -1c
.RI "void \fBsetVille\fP (std::string v)"
.br
.ti -1c
.RI "void \fBsetNbVentes\fP (unsigned int n)"
.br
.ti -1c
.RI "void \fBsetNbAchats\fP (unsigned int n)"
.br
.ti -1c
.RI "void \fBsetNote\fP (unsigned int n)"
.br
.ti -1c
.RI "void \fBaddAchat\fP (\fBProduit\fP *p)"
.br
.ti -1c
.RI "void \fBaddVente\fP (\fBProduit\fP *p)"
.br
.ti -1c
.RI "void \fBaddAvis\fP (\fBAvis\fP a)"
.br
.ti -1c
.RI "std::string \fBtoString\fP ()"
.br
.ti -1c
.RI "void \fBdecrit\fP (std::ostream &os)"
.br
.ti -1c
.RI "std::string \fBdecrit\fP ()"
.br
.ti -1c
.RI "void \fBaffiche\fP (std::ostream &os)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EMarche from the source code\&.
