.TH "VenteNormale" 3 "Thu Dec 17 2015" "EMarche" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VenteNormale \- 
.PP
Cette classe gère une vente normale\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VenteNormale\&.h>\fP
.PP
Inherits \fBEtatVente\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVenteNormale\fP (bool b)"
.br
.RI "\fIConstructeur de la classe \fBVenteNormale\fP\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Cette classe gère une vente normale\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VenteNormale::VenteNormale (boolb)"

.PP
Constructeur de la classe \fBVenteNormale\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIb\fP - Booléen qui donne le type de la vente 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for EMarche from the source code\&.
